DATA SEGMENT
    NUM DW 0019H, 2301H
    SUM DW 2 DUP(0)
DATA ENDS 

CODE SEGMENT
    ASSUME CS: CODE, DS:DATA
    START: MOV AX,DATA
    MOV DS,AX
    MOV AX,NUM
    MOV BX,0H
    ADD AX, NUM+2
    JNC DOWN
    INC BX
    DOWN: MOV SUM,AX
    MOV SUM+2,BX
    MOV AH,4CH
CODE ENDS
END START
