;19BCE2301 DEEP HIREN KOTECHA
;32-BIT ADDITION

DATA SEGMENT 
    NUM1 DW 0019H, 2301H
    NUM2 DW 2301H, 0019H
    SUM DW 4 DUP<0>
    DATA ENDS
CODE SEGMENT
    ASSUME CS:CODE, DS:DATA
    START:MOV AX,DATA
    MOV DS,AX
    MOV AX,NUM1
    ADD AX,NUM2
    MOV SUM,AX
    MOV AX,NUM1+2
    ADC AX,NUM2+2
    JNC DOWN
    MOV SUM+4,01H
    DOWN: MOV SUM+2,AX
    MOV AH,4CH
    INT 21H
    CODE ENDS
END START